


[package]
name = "vifs"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "vifs"
# path = "src/include/lib.rs"

[alias]
t = "test -- --nocapture"

[dependencies]
sha2 = "0.10.8"
uuid = { version = "1.0", features = ["v4"]}
md-5 = "0.10.5"