


[package]
name = "vifs"
version = "0.1.0"
edition = "2021"

[alias]
t = "test -- --nocapture"

[[bin]]
name = "fsd"
path = "src/bin/fsd.rs"

# [features]
# windows_by_handle = []

[dependencies]
sha2 = "0.10.8"
uuid = { version = "1.0", features = ["v4"]}
md-5 = "0.10.5"